import "./globals.css";
import { Poppins } from 'next/font/google'
import Navbar from '@/app/component/layers/Navbar'
import Footer from "./component/layers/Footer";
import StoreProvider from "./StoreProvider";

const popins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
})

export const metadata = {
  title: "TechStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${popins.className}`}>
        <StoreProvider>
            <Navbar />
              {children}
            <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
