import React from 'react'
import BlogItem from './BlogItem'
import Container from './Container'

const Blogs = () => {
  return (
    <Container>
    <div className="grid grid-cols-12 gap-x-2 gap-y-5 w-full bg-lime-400">
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
        <BlogItem className='' />
       
    </div>
</Container>
  )
}

export default Blogs

